group:
  # all projects
  - repos: |
      conda/.github
      conda/actions
      conda/conda
      conda/conda-benchmarks
      conda/conda-build
      conda/conda-content-trust
      conda/conda-docs
      conda/conda-index
      conda/conda-pack
      conda/conda-package-handling
      conda/conda-plugin-template
      conda/conda-prefix-replacement
      conda/conda-standalone
      conda/conda-verify
      conda/constructor
      conda/cookiecutter-conda-python
      conda/issue-tracker
      conda/menuinst
      conda/pycosat
      conda/schemas
    files:
      # beta project
      - source: .github/workflows/project.yml
        dest: .github/workflows/project.yml
      # issue logic
      - source: .github/workflows/issues.yml
        dest: .github/workflows/issues.yml
      # label syncing
      - source: .github/workflows/labels.yml
        dest: .github/workflows/labels.yml
      # stale issues
      - source: .github/workflows/stale.yml
        dest: .github/workflows/stale.yml
      # lock issues
      - source: .github/workflows/lock.yml
        dest: .github/workflows/lock.yml
      # CLA check
      - source: .github/workflows/cla.yml
        dest: .github/workflows/cla.yml
      # issue forms
      - source: .github/ISSUE_TEMPLATE/0_bug.yml
        dest: .github/ISSUE_TEMPLATE/0_bug.yml
      - source: .github/ISSUE_TEMPLATE/1_feature.yml
        dest: .github/ISSUE_TEMPLATE/1_feature.yml
      - source: .github/ISSUE_TEMPLATE/epic.yml
        dest: .github/ISSUE_TEMPLATE/epic.yml
      # issue sorting
      - source: HOW_WE_USE_GITHUB.md
        dest: HOW_WE_USE_GITHUB.md
  # projects with releases
  - repos: |
      conda/actions
      conda/conda
      conda/conda-benchmarks
      conda/conda-build
      conda/conda-content-trust
      conda/conda-docs
      conda/conda-index
      conda/conda-pack
      conda/conda-package-handling
      conda/conda-prefix-replacement
      conda/conda-standalone
      conda/conda-verify
      conda/constructor
      conda/cookiecutter-conda-python
      conda/menuinst
      conda/pycosat
      conda/schemas
    files:
      # PR template
      - source: .github/PULL_REQUEST_TEMPLATE/with_releases.md
        dest: .github/PULL_REQUEST_TEMPLATE.md
      # news snippet template
      - source: .github/sync/TEMPLATE
        dest: news/TEMPLATE
  # projects without releases
  - repos: |
      conda/.github
      conda/conda-plugin-template
      conda/issue-tracker
    files:
      # PR template
      - source: .github/PULL_REQUEST_TEMPLATE/without_releases.md
        dest: .github/PULL_REQUEST_TEMPLATE.md
  # projects with rever releases
  - repos: |
      conda/conda
      conda/conda-build
      conda/conda-package-handling
    files:
      # rever config
      - source: .github/sync/rever.xsh
        dest: rever.xsh
      # release docs
      - source: .github/sync/RELEASE.md
        dest: RELEASE.md
  # Code of Conduct sync
  - repos: |
      conda/.github
      conda/actions
      conda/conda
      conda/conda-benchmarks
      conda/conda-build
      conda/conda-content-trust
      conda/conda-docs
      conda/conda-index
      conda/conda-pack
      conda/conda-package-handling
      conda/conda-package-streaming
      conda/conda-plugin-template
      conda/conda-prefix-replacement
      conda/conda-standalone
      conda/conda-verify
      conda/constructor
      conda/cookiecutter-conda-python
      conda/issue-tracker
      conda/menuinst
      conda/pycosat
      conda/schemas
    files:
      - source: CODE_OF_CONDUCT.md
        dest: CODE_OF_CONDUCT.md
