---
name: Add News

on:
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - reopened
      - opened
      - synchronize

jobs:
  check:
    if: >-
      !github.event.repository.fork && (
        github.event.comment.body == 'please add news'
        || github.event_name == 'pull_request_target'
      )

    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Add emoji reaction
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: '+1'

      - name: News file from template
        run: |
          cp news/TEMPLATE "news/${{ github.event.issue.number }}_${{ steps.extract_branch.outputs.branch }}"

      - name: Check status of the (presumed) PR branch
        run: |
          git status
          git checkout -b $RANDOM

      - name: Commit and Add New News File to the Pull Request
        uses: EndBug/add-and-commit@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "Add news file to this PR"
          add: "news/${{ github.event.issue.number }}_${{ steps.extract_branch.outputs.branch }}"
          branch: ${{ steps.extract_branch.outputs.branch }}
          push: true
