---
name: Add News

on:
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - reopened
      - opened
      - synchronize

jobs:
  check:
    if: >-
      !github.event.repository.fork && (
        github.event.comment.body == '@conda-bot please add news'
        || github.event_name == 'pull_request_target'
      )

    runs-on: ubuntu-latest
    steps:
      - name: Extract PR branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: pr_branch_name

      - name: Extract PR number
        shell: bash
        run: echo ${{ github.event.pull_request.number }}
        id: pr_number

      - name: Create File
        if: contains(steps.check_comment.outputs.comment, 'please add news')
        id: create_file
        uses: actions/checkout@v2

      - name: Populate File
        uses: 1arp/create-a-file-action@0.2
        with:
          path: "news"
          file: "${{ steps.pr_number }}-${{ steps.pr_branch_name }}"
          content: |
            ### Enhancements

            * <news item>

            ### Bug fixes

            * <news item>

            ### Deprecations

            * <news item>

            ### Docs

            * <news item>

            ### Other

            * <news item>

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Commit File
        if: steps.create_file.outputs
        run: |
          git config --local user.email user@example.com
          git config --local user.name ${{ github.actor }}
          git add .
          git commit -m "Add news snippet"
          git push
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
